ongr-io/ElasticsearchDSL

src/Search.php
src/SearchEndpoint/AbstractSearchEndpoint.php
src/SearchEndpoint/QueryEndpoint.php
src/Serializer/Normalizer/AbstractNormalizable.php
src/Serializer/Normalizer/CustomReferencedNormalizer.php
src/Serializer/Normalizer/OrderedNormalizerInterface.php
src/Serializer/OrderedSerializer.php
tests/SearchTest.php

Some dependencies were missing for `ONGR\ElasticsearchDSL\Search`. I backported those from `ONGR\ElasticsearchBundle`.

Fix missing dependencies for Search class

---

src/Search.php

Suggester namespace was removed in commit 832934df690857c457b5f69f3fc433e8e6f0aa08.

Remove remaining occurences of suggester

---

src/Query/FunctionScoreQuery.php

In method addFieldValueFactorFunction.
Elasticsearch documentation says that it is optional.

Make modifier argument optional.

---

src/Query/FunctionScoreQuery.php

In method addRandomFunction.
Elasticsearch expects object not array and empty array will not be made into object.

Use empty stdClass instead of empty array.

---

src/Search.php

https://github.com/ongr-io/ElasticsearchDSL/blob/master/docs/Filter/Post.md with Bool example giving wrong results because at `Search->addPostFilter->add`  was giving parameters  (`$filter, $boolType, $key`), and the `add` method accepting only 2 parameters (`BuilderInterface $builder, $key = null`).

fixed bug for addPostFilter when using wrong Interface

---

src/Query/FunctionScoreQuery.php

before we had
``` json
{
"script": "...",
"params": {},
"0"
}
```

Function script score options are now being merged

---

.travis.yml
composer.json
docs/Aggregation/TopHits.md
src/SearchEndpoint/SortEndpoint.php

- Using `FieldSort`, instead of `Sort` object
- Replace `ONGR Strick Standard` by `PSR2`

Adapt to support ESB v1.0.*

---

.coveralls.yml
.travis.yml
composer.json

Coveralls integration. IMHO we really need to think about adding such dependencies into composer.json
Also added PHP 5.4 to Travis config which was removed somehow.
Closes #40

Coveralls integration

---

src/Aggregation/FilterAggregation.php
src/Query/BoolQuery.php
src/SearchEndpoint/FilterEndpoint.php
src/SearchEndpoint/PostFilterEndpoint.php
src/SearchEndpoint/QueryEndpoint.php
tests/Query/BoolQueryTest.php
tests/Query/NestedQueryTest.php
tests/SearchEndpoint/FilterEndpointTest.php
tests/SearchEndpoint/PostFilterEndpointTest.php
tests/SearchEndpoint/QueryEndpointTest.php

Fixes #32
This PR deprecates `BoolQuery::isRelevant()` because it complicates everything. Too many places uses that complicated logic. Idea is "keep things simple, use single (full) query structure".
After these changes queries with single must bool will look like this:
```json
{"bool":{"must":[{"match_all":[]}]}}
```
Instead of this:
```json
{"match_all":[]}
```
Both ways are valid and equal. This does not influence results returned by Elasticsearch.
In the future we could simplify structure again, BUT only if we could do that in `BoolQuery` itself. That would be a BC break. I think each query class itself should return full array (`[type=>data_array]`).
Please merge this only after #48 is merged.

Fix nested query in case "bool" with single "must" given

---

src/Query/BoolQuery.php
tests/Query/BoolQueryTest.php

This PR adds `filter` type support for `bool` query (Elasticsearch 2.0 feature).
This will allow us to deprecate all filters and implement full "query in filter context" support.

Add filter clause for BoolQuery

---

CHANGELOG.md
src/Aggregation/AbstractAggregation.php
src/SearchEndpoint/FilterEndpoint.php
tests/Aggregation/FilterAggregationTest.php
tests/Aggregation/NestedAggregationTest.php
tests/Aggregation/RangeAggregationTest.php

Please note, this is partial __BC break__. Output now wont have `agg_` prefix. This should not affect users who were using `PREFIX` constant.

[Proposal] Do not add prefix for aggregation names

---

CHANGELOG.md
docs/HowTo/HowToSearch.md
docs/Query/Filtered.md
src/BuilderInterface.php
src/DslTypeAwareTrait.php
src/FilterOrQueryDetectionTrait.php
src/Query/TypeQuery.php
src/Search.php
src/SearchEndpoint/FilterEndpoint.php
tests/Aggregation/FilterAggregationTest.php
tests/Query/GeoBoundingBoxQueryTest.php
tests/Query/HasChildQueryTest.php
tests/Query/HasParentQueryTest.php
tests/SearchEndpoint/FilterEndpointTest.php
tests/SearchEndpoint/PostFilterEndpointTest.php

- Deprecated `DslTypeAwareTrait` and `FilterOrQueryDetectionTrait` traits as they wont be needed after we remove filters.
- Fixed `GeoBoundingBoxQueryTest` as it was testing filter, not query.
- Replaced filter class usages with queries where possible.

Deprecate filter/query detection traits

---

src/SearchEndpoint/QueryEndpoint.php

Follows https://github.com/ongr-io/ElasticsearchBundle/pull/543

Do not set filtered query into query endpoint during normalization

---

README.md

Warned about legacy ES version in AWS Elasticsearch Service

AWS ES warning

---

composer.json

Remove `symfony/options-resolver` dependency from composer.json as it's not used anywhere in the code.

Remove unused symfony/options-resolver dependency

---

README.md

Amazon Elasticsearch Service now supports Elasticsearch 2.3.
See: https://aws.amazon.com/about-aws/whats-new/2016/07/amazon-elasticsearch-service-now-supports-elasticsearch-2-3

Remove Amazon Elasticsearch Service version warning

---

src/Aggregation/AbstractAggregation.php

With php7 new uniform syntax, we can do `(new Object())->call()`
This simple patch allow to avoid declare a variable for nested aggregation, and keep code more readable : 
```php
$query = (new Search())
->addAggregation(new TermsAggregation("country", 'organization_address.city'))
->addAggregation((new ChildrenAggregation("article", 'article'))
->addAggregation(new TermsAggregation("name", 'article_name.fr'))
->addAggregation((new NestedAggregation("kind", 'article_kind'))
->addAggregation(new TermsAggregation('name', 'kind_name.fr.original'))
)
);
```

Allow chaining of aggregation

---

docs/InnerHits/Nested.md
src/InnerHit/NestedInnerHit.php
tests/InnerHit/NestedInnerHitTest.php
tests/InnerHit/ParentInnerHitTest.php

Hi, 
It's not a full pull request but more a implementation question that need some more work to be completed (tests).
InnerHits support mostly all parameters available for search (from, size, highlight, source, ...)
The current implementation as partial support for this parameters (from some via addParameters).
My proposal is to give a full search to innerhits, It's more user friendly.
In case you agree, you can close this one : https://github.com/ongr-io/ElasticsearchDSL/pull/153 that will be duplicate.
What do you think about it ?

InnerHit new implementation

---

src/Aggregation/Bucketing/HistogramAggregation.php

At the moment, a 0 value for min extended bounds gets filtered and is not sent in the request.

Allow min=0 for extended bounds

---

src/Search.php

'_source_exclude' and '_source_include' was missing in parameters whitelist.

Adding missing URI parameters

---

composer.json
src/Search.php

There are situation where adding multiple queries is super beneficial. 
This PR enables package users to call `$search->addQueries(...)` in two different ways.
In this case an array of `BuilderInterface $query` are passed to the root `$search->addQuery()` function.
In this case an array of arrays is passed in, each member of the array is to match the function signature of `$search->addQuery()` and the PHP 5.4 traversable unpacking language feature is used to parameterise the root `$search->addQuery()` function.

Ability to add multiple queries in a single call

---

src/Aggregation/Bucketing/DateRangeAggregation.php
src/Aggregation/Bucketing/GeoDistanceAggregation.php
src/Aggregation/Bucketing/Ipv4RangeAggregation.php
src/Aggregation/Bucketing/RangeAggregation.php

fixes #255 - added null check to array_filter to allow `0` values to pass through
Example `['from' => 0, 'to' => 0]` is a valid aggregate range

fixes #255 - added null check to array_filter 

---

src/Search.php

With the current implementation, new Serializer will be created for every instance of Search class. Depending on the amount of created instances, this may add noticeable overhead.
Now the Serializer instance will be created once and reused from that on.

Serializer in search should be static

---

src/Query/Compound/FunctionScoreQuery.php

A getQuery Method added to FunctionScoreQuery.php.
Developers can use the method in order to apply some changes to query of FunctionScoreQuery.

Add getQuery Method to FunctionScoreQuery

---

src/Sort/FieldSort.php
src/Sort/NestedSort.php
tests/Unit/Sort/FieldSortTest.php
tests/Unit/Sort/NestedSortTest.php

Includes unit tests
fixes https://github.com/ongr-io/ElasticsearchDSL/issues/266
Note that this is only working in 6.1. You probably need a separate branch for 6.0 if you want this 6.1 feature.
Sample usage:
```php
$sort = new FieldSort('someField', 'asc');
$nestedFilter = new NestedSort('somePath', new TermQuery('somePath.id', 10));
$sort->setNestedFilter($nestedFilter);
var_dump($sort->toArray());
```
Nested filter can be nested by calling `setNestedFilter` on a `NestedSort`

added new NestedSort for replacing deprecated nested_filter and nested_path

---

src/Query/TermLevel/TermQuery.php

Since Elasticsearch supports more than just strings, I think it would be a good addition to allow those values in the constructor of `TermQuery` to reflect this.
We're currently trying to improve the depth of the static code analysis of our project. While doing so, this issue showed up. We are using the `TermQuery` with bool or integer values, which shouldn't be possible according to the current typehints.

Allow more scalar values in TermQuery

---

src/Search.php
src/SearchEndpoint/SearchEndpointInterface.php

To get the available hits, it has to return the exact class. Also, the class shouldn't change.

fix get bool doctype to get available typehints

---

src/Query/FullText/MultiMatchQuery.php
tests/Unit/Query/FullText/MultiMatchQueryTest.php

From the Elasticsearch documentation:
> If no fields are provided, the multi_match query defaults to the `index.query.default_field` index settings, which in turn defaults to `*`. `*` extracts all fields in the mapping that are eligible to term
queries and filters the metadata fields. All extracted fields are then combined to build a query.

Update to allow multi-match query with no fields

---

src/Query/Compound/BoolQuery.php
tests/Unit/Query/Compound/BoolQueryTest.php

Since `BoolQuery@add` isn't chainable, this provides a convenient/clean way to build a `BoolQuery` object
Example:
```php
$bool = new BoolQuery([
BoolQuery::SHOULD => [new TermQuery('key1', 'value1')],
BoolQuery::MUST => [
new TermQuery('key2', 'value2'),
new TermQuery('key3', 'value3'),
],
BoolQuery::MUST_NOT => new TermQuery('key4', 'value4')
]);
```

[6.x] BoolQuery constructor allows building container

---

src/Search.php

We are using static analyzing for our code and because of these not complete type hints, we get errors.

Add nullable for size and from methods

---

src/ParametersTrait.php

Parameters like "boost" are floats (default Value is 1.0). So a static analysis could show errors here.

Add float as parameters hint for static analysis
