composer.json, src/Search.php, src/SearchEndpoint/AbstractSearchEndpoint.php, src/SearchEndpoint/QueryEndpoint.php, src/Serializer/Normalizer/AbstractNormalizable.php, src/Serializer/Normalizer/CustomReferencedNormalizer.php, src/Serializer/Normalizer/OrderedNormalizerInterface.php, src/Serializer/OrderedSerializer.php, tests/SearchEndpoint/QueryEndpointTest.php, tests/SearchTest.php
Note: This PR includes commits from #1.
Relevant commit is the second one.
=> Fix query endpoint dependency

tests/Query/FunctionScoreQueryTest.php
=> Add FunctionScoreQuery::addFieldValueFactorFunction test.

tests/Query/FunctionScoreQueryTest.php
In method FunctionScoreQueryTest::addRandomFunction.
=> Test usage of empty stdClass.

src/Aggregation/AbstractAggregation.php, src/Aggregation/ChildrenAggregation.php, src/Aggregation/DateRangeAggregation.php, src/Aggregation/ExtendedStatsAggregation.php, src/Aggregation/FilterAggregation.php, src/Aggregation/FiltersAggregation.php, src/Aggregation/GeoBoundsAggregation.php, src/Aggregation/GeoDistanceAggregation.php, src/Aggregation/GeoHashGridAggregation.php, src/Aggregation/HistogramAggregation.php, src/Aggregation/Ipv4RangeAggregation.php, src/Aggregation/MissingAggregation.php, src/Aggregation/NestedAggregation.php, src/Aggregation/PercentileRanksAggregation.php, src/Aggregation/PercentilesAggregation.php, src/Aggregation/RangeAggregation.php, src/Aggregation/ReverseNestedAggregation.php, src/Aggregation/StatsAggregation.php, src/Aggregation/TermsAggregation.php, tests/Aggregation/DateRangeAggregationTest.php, tests/Aggregation/FilterAggregationTest.php, tests/Aggregation/FiltersAggregationTest.php, tests/Aggregation/GeoDistanceAggregationTest.php, tests/Aggregation/Ipv4RangeAggregationTest.php, tests/Aggregation/PercentileRanksAggregationTest.php, tests/Aggregation/PercentilesAggregationTest.php, tests/Aggregation/RangeAggregationTest.php, tests/Aggregation/StatsAggregationTest.php
Edit constructors to accept used parameters to simplify usage.
=> Aggregation constructors

src/Aggregation/TopHitsAggregation.php, tests/Aggregation/TopHitsAggregationTest.php
=> Fix top hits aggregation to respect set parameters.

src/Query/FunctionScoreQuery.php
=> options now is optional argument for addDecayFunction.

docs/HowTo/CustomParameters.md, docs/index.md, src/Search.php, tests/SearchTest.php
=> Missing parameters for request

composer.json
Hi all tests are good. Lets go!
=> sf3 support

CHANGELOG.md, docs/Query/FuzzyLikeThisField.md, docs/Query/FuzzyLikeThisQuery.md, src/Query/FuzzyLikeThisFieldQuery.php, src/Query/FuzzyLikeThisQuery.php
These queries are removed in Elasticsearch v2.0
=> Mark FuzzyLikeThis classes as deprecated

src/Aggregation/TopHitsAggregation.php, src/Sort/FieldSort.php, tests/SearchTest.php
=> Fix query sort structure

docs/Suggest/index.md, docs/index.md
@saimaz I think it would be nice if ElasticsearchDSL supports all types of suggest. Currently only Term suggest is supported. I can take care of that. What do you think?
=> Added documentation about suggest

src/Search.php, src/SearchEndpoint/SuggestEndpoint.php, src/Suggest/TermSuggest.php, tests/SearchEndpoint/SuggestEndpointTest.php, tests/SearchTest.php, tests/Suggest/TermSuggestTest.php
added name to toArray() method, made SuggestEndpoint handle many requests
=> changed Suggest to TermSuggest

src/Aggregation/NestedAggregation.php, tests/Aggregation/NestedAggregationTest.php
references:
https://github.com/ongr-io/ElasticsearchBundle/issues/473
=> removed the exception from nestedAggregation

src/Suggest/CompletionSuggest.php, tests/Suggest/CompletionSuggestTest.php
=> added completion suggester and its test

src/Search.php
=> Clean use statements

src/Search.php
Add missing parameter type annotations
=> Remove unused parameters

src/Aggregation/FiltersAggregation.php, tests/Aggregation/FiltersAggregationTest.php, tests/Integration/SearchTest.php
* Added integration tests of documentation examples.
* Fixed unit tests of `FilterAggregation`.
* Fixed `FilterAggregation`.
Fixes #91.
=> Fix returned array of FiltersAggregation

src/Query/IdsQuery.php, src/Query/Span/SpanNotQuery.php
Removed TODO annotations. Created issues: #85, #86.
=> Remove TODOs

src/Sort/FieldSort.php
=> added parameter trait to FieldSort

src/Query/Span/SpanNotQuery.php
=> implemented option support in SpanNotQuery

src/Query/MatchPhrasePrefixQuery.php, src/Query/MatchPhraseQuery.php, tests/Query/MatchPhrasePrefixQueryTest.php, tests/Query/MatchPhraseQueryTest.php
=> Added query objects for match_phrase and match_phrase_prefix

docs/Aggregation/DateHistogram.md, src/Aggregation/DateHistogramAggregation.php, tests/Aggregation/DateHistogramAggregationTest.php
=> added date histogram aggregation

docs/Aggregation/SignificantTerms.md, src/Aggregation/SignificantTermsAggregation.php, tests/Aggregation/SignificantTermsAggregationTest.php
=> added significant terms aggregation

src/Query/FunctionScoreQuery.php
=> Fix bug for functionscore functions filters implementation

docs/Query/SpanContaining.md, src/Query/Span/SpanContainingQuery.php, tests/Query/Span/SpanContainingQueryTest.php
=> added SpanContaining query

docs/Query/SpanContaining.md, docs/Query/SpanWithin.md, src/Query/Span/SpanContainingQuery.php, src/Query/Span/SpanWithinQuery.php, tests/Query/Span/SpanContainingQueryTest.php, tests/Query/Span/SpanWithinQueryTest.php
Do not merge until #102 
Part of #97
=> added span within query

src/InnerHit/AbstractInnerHit.php, src/Search.php, src/SearchEndpoint/InnerHitsEndpoint.php, src/SearchEndpoint/SearchEndpointFactory.php, tests/SearchEndpoint/InnerHitsEndpointTest.php
=> Added inner hits endpoint

docs/Query/Template.md, src/Query/TemplateQuery.php, tests/Query/TemplateQueryTest.php
=> added template query

src/Aggregation/Pipeline/AbstractPipelineAggregation.php
This is the abstraction for the upcoming series of pipeline aggregations, that will be based on this abstraction class after a rethink on the structure of extensions
Part of #112
=> Added abstract pipeline aggregation

docs/Aggregation/Pipeline/MaxBucket.md, src/Aggregation/Pipeline/MaxBucketAggregation.php, tests/Aggregation/Pipeline/MaxBucketAggregationTest.php
=> Added max bucket pipeline aggregation

docs/Aggregation/Pipeline/AvgBucket.md, src/Aggregation/Pipeline/AvgBucketAggregation.php, tests/Aggregation/Pipeline/AvgBucketAggregationTest.php
=> Added avg_bucket pipeline aggregation

docs/Aggregation/SamplerAgg.md, src/Aggregation/SamplerAggregation.php, tests/Aggregation/SamplerAggregationTest.php
=> added sampler aggregation

docs/Aggregation/GeoCentroid.md, src/Aggregation/GeoCentroidAggregation.php, tests/Aggregation/GeoCentroidAggregationTest.php
=> added geo centroid aggregation

docs/Aggregation/Pipeline/Derrivative.md, src/Aggregation/Pipeline/DerivativeAggregation.php, tests/Aggregation/Pipeline/DerivativeAggregationTest.php
=> Added derivative pipeline aggregation

docs/Aggregation/Pipeline/MinBucket.md, src/Aggregation/Pipeline/MinBucketAggregation.php, tests/Aggregation/Pipeline/MinBucketAggregationTest.php
=> Added min bucket pipeline aggregation

docs/Aggregation/Pipeline/SerialDifferencing.md, src/Aggregation/Pipeline/SerialDifferencingAggregation.php, tests/Aggregation/Pipeline/SerialDifferencingAggregationTest.php
=> Added serial differencing pipeline aggregation

docs/Aggregation/Pipeline/BucketScript.md, docs/Aggregation/Pipeline/BucketSelector.md, src/Aggregation/Pipeline/BucketScriptAggregation.php, src/Aggregation/Pipeline/BucketSelectorAggregation.php, tests/Aggregation/Pipeline/BucketScriptAggregationTest.php, tests/Aggregation/Pipeline/BucketSelectorAggregationTest.php
=> Added bucket selector pipeline aggregation

docs/Aggregation/Pipeline/CumulativeSum.md, src/Aggregation/Pipeline/CumulativeSumAggregation.php, tests/Aggregation/Pipeline/CumulativeSumAggregationTest.php
=> Added cumulative sum pipeline aggregation

docs/Aggregation/Pipeline/StatsBucket.md, src/Aggregation/Pipeline/StatsBucketAggregation.php, tests/Aggregation/Pipeline/StatsBucketAggregationTest.php
=> Added stats pipeline aggregation

docs/Aggregation/Pipeline/ExtendedStatsBucket.md, src/Aggregation/Pipeline/ExtendedStatsBucketAggregation.php, tests/Aggregation/Pipeline/ExtendedStatsBucketAggregationTest.php
=> Added extended stats pipeline aggregation

docs/Aggregation/Pipeline/SumBucket.md, src/Aggregation/Pipeline/SumBucketAggregation.php, tests/Aggregation/Pipeline/SumBucketAggregationTest.php
Documentation will be added after confirmation
Part of #112
=> Added sum bucket pipeline aggregation

docs/Aggregation/Pipeline/PercentilesBucket.md, src/Aggregation/Pipeline/PercentilesBucketAggregation.php, tests/Aggregation/Pipeline/PercentilesBucketAggregationTest.php
=> Added percentile pipeline aggregation

src/Aggregation/CardinalityAggregation.php
Just to be consistent with other aggregation
=> Missing construct on CardinalityAggregation

src/Aggregation/NestedAggregation.php, src/Aggregation/ReverseNestedAggregation.php
=> Fixes nested and reverse nested aggregation requirements

src/Query/BoolQuery.php, tests/Query/BoolQueryTest.php
=> Fix notice in BoolQuery::getQueries when nothing is added to bool type

composer.json, src/Query/BoolQuery.php
=> Use random_bytes instead of uniqid

composer.json, src/Search.php, tests/Unit/SearchTest.php
=> add scroll to URI parameters, fixes #201

docs/Query/Geo/GeoBoundingBox.md
=> Added documenteation for geo bounding box query

docs/Query/Span/SpanMultiTerm.md
=> Added docs for span multi term query

docs/Query/Span/SpanFirst.md
=> Added docs for span first query

docs/Query/Geo/GeoPolygon.md
=> Added documentation for geo polygon query

docs/Query/Geo/GeoDistance.md
=> Added docs for geo distance query

docs/Query/FullText/MatchPhrase.md
=> Added docs for match phrase query

docs/Query/FullText/MatchPhrasePrefix.md
=> added match phrase prefix query documentation

docs/Query/Geo/GeoDistanceRange.md, src/Query/Geo/GeoDistanceRangeQuery.php
=> Docs for geo distance range query

docs/Query/Span/SpanNear.md
=> Added documentation for span near query

src/Query/Joining/NestedQuery.php
Currently there is not possibility to get query object when it is wrapped inside nested query.
=> Getter for nested query and path.

composer.json
Update for #227 for the `5.x` branch.
=> Allow lower random_compat version

src/BuilderBag.php, src/SearchEndpoint/AbstractSearchEndpoint.php
=> Replace remaining usages of uniqid with random_bytes

src/Query/Geo/GeoShapeQuery.php, tests/Unit/Query/Geo/GeoShapeQueryTest.php
Fixes https://github.com/ongr-io/ElasticsearchDSL/issues/220
=> implemented relation for geo_shape query

src/Aggregation/Bucketing/DateRangeAggregation.php
(cherry picked from commit 8458ac9)
=> fixes #237 - added support for date range keys

docs/Aggregation/TopHits.md, src/Aggregation/Metric/TopHitsAggregation.php, tests/Unit/Aggregation/Metric/TopHitsAggregationTest.php
=> fixed top hits sort deprecated issue

src/Aggregation/Bucketing/DateHistogramAggregation.php
Feature/5.x 257 datehistogram format
=> fixes #257 - added $format arg to date histogram

src/Query/Compound/BoolQuery.php, tests/Unit/Query/Compound/BoolQueryTest.php
=> fix bool query when the body is empty

src/ParametersTrait.php
Like before, I added some more scalar types to the method's typehints.
=> Add more scalar types to function ParametersTrait

.travis.yml, src/Query/Geo/GeoShapeQuery.php, tests/Unit/Query/Geo/GeoShapeQueryTest.php
=> Added relation parameter for pre-indexed geo_shape query
